# Generated by Django 4.1.3 on 2022-11-13 23:45

from django.db import migrations
from ..models import Word

def init_insert(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    # Word = apps.get_model('word', 'Word')

    file = open("word/migrations/words.txt", "r")
    for w in file:
        w = w[:-1]
        word = Word(word=w, word_ac=w)
        word.save()

class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_insert),
    ]
